puts "🌱 Seeding spices..."

# Seed your database here

chest = Category.create(category: "Chest")
legs = Category.create(category: "Legs")
back = Category.create(category: "Back")
abs = Category.create(category: "Abs")
arms = Category.create(category: "Arms")
flex = Category.create(category: "Flex")
cardio = Category.create(category: "Cardio")

Exercise.create(name: "Push ups", note: "Can do on knees or toes", category_id: chest.id)
Exercise.create(name: "Plank", note: "Can do on knees or toes", category_id: chest.id)
Exercise.create(name: "Burpees", note: "Can add a jump at end", category_id: chest.id)
Exercise.create(name: "Dips", note: "Need dip stand or similar", category_id: chest.id)
Exercise.create(name: "Incline push-ups", note: "Arms are raised", category_id: chest.id)
Exercise.create(name: "Decline push-ups", note: "Legs are raised", category_id: chest.id)
Exercise.create(name: "Squats", note: "Narrow or wide leg stance", category_id: legs.id)
Exercise.create(name: "Lunge", note: "Knee to touch floor", category_id: legs.id)
Exercise.create(name: "Reverse lunge", note: "Knee to touch floor", category_id: legs.id)
Exercise.create(name: "Jump squats", note: "Wide leg stance", category_id: legs.id)
Exercise.create(name: "Glute bridge", note: "Keep core tight", category_id: legs.id)
Exercise.create(name: "Calf raises", note: "Use step or similar", category_id: legs.id)
Exercise.create(name: "Superman", note: "Keep core tight", category_id: back.id)
Exercise.create(name: "Pull-ups", note: "Can do with bands", category_id: back.id)
Exercise.create(name: "Inverted row", note: "Can use bedsheet", category_id: back.id)
Exercise.create(name: "Plank row", note: "Can use dumbbells", category_id: back.id)
Exercise.create(name: "Bird dog", note: "Keep core tight", category_id: back.id)
Exercise.create(name: "Lower back extension", note: "Keep core tight", category_id: back.id)
Exercise.create(name: "Crunch", note: "Can use medicine ball", category_id: abs.id)
Exercise.create(name: "V-ups", note: "Keep arms and legs straight", category_id: abs.id)
Exercise.create(name: "Reverse crunch", note: "Keep core tight", category_id: abs.id)
Exercise.create(name: "Flutter kicks", note: "Keep core tight", category_id: abs.id)
Exercise.create(name: "Sit ups", note: "Can use medicine ball", category_id: abs.id)
Exercise.create(name: "Russian twist", note: "Can use medicine ball", category_id: abs.id)
Exercise.create(name: "Tricep dips", note: "Can use chair or bar", category_id: arms.id)
Exercise.create(name: "Crab crawl", note: "Keep body high and tight", category_id: arms.id)
Exercise.create(name: "Tricep push-ups", note: "Can do on knees", category_id: arms.id)
Exercise.create(name: "Chin ups", note: "Can use a band", category_id: arms.id)
Exercise.create(name: "Pike push-ups", note: "Keep core tight", category_id: arms.id)
Exercise.create(name: "Plank up and downs", note: "Keep core tight", category_id: arms.id)
Exercise.create(name: "Run", note: "Run as fast as you can", category_id: cardio.id)
Exercise.create(name: "Skip", note: "Single or double skips", category_id: cardio.id)
Exercise.create(name: "Box jump", note: "Can use low or high box", category_id: cardio.id)
Exercise.create(name: "Jumping jacks", note: "Keep core tight", category_id: cardio.id)
Exercise.create(name: "High knees", note: "Keep core tight", category_id: cardio.id)
Exercise.create(name: "Butt kicks", note: "Keep core tight", category_id: cardio.id)
Exercise.create(name: "Knee to chest", note: "30 sec each side", category_id: flex.id)
Exercise.create(name: "Quad stretch", note: "30 sec each side", category_id: flex.id)
Exercise.create(name: "Sphinx pose", note: "Elbows under shoulders", category_id: flex.id)
Exercise.create(name: "Downward dog pose", note: "Keep core tight", category_id: flex.id)
Exercise.create(name: "Shoulder roll", note: "Keep core tight", category_id: flex.id)
Exercise.create(name: "Crossbody stretch", note: "30 sec each side", category_id: flex.id)
Exercise.create(name: "Butterfly stretch", note: "Knees to floor", category_id: flex.id)
Exercise.create(name: "Triceps stretch", note: "30 sec each side", category_id: flex.id)
Exercise.create(name: "Hamstring stretch", note: "30 sec each side", category_id: flex.id)
Exercise.create(name: "Cat-cow pose", note: "Inhale up, exhale down", category_id: flex.id)
Exercise.create(name: "Runner’s lunge", note: "30 sec each side", category_id: flex.id)
Exercise.create(name: "Pidgeon pose", note: "30 sec each side", category_id: flex.id)


puts "✅ Done seeding!"

